In [106]:
import pandas as pd
import sklearn
import nltk
import numpy as np
import re
import seaborn as sns

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

ImportError: cannot import name 'pad_sequences' from 'keras.preprocessing.sequence' (C:\Users\sriva\Python\lib\site-packages\keras\preprocessing\sequence.py)

In [109]:
# Importing all the necessary libraries
import keras
import h5py
from keras import optimizers
from keras.models import load_model
from keras.layers import Bidirectional
#from Multimodal_baseline_Functions import *
from keras.layers.core import Reshape, Dropout
from keras.utils.vis_utils import plot_model
import os
# import keras_metrics
import matplotlib.pyplot as plt
from keras.layers import Conv1D, MaxPooling1D, Flatten, GlobalAveragePooling3D
from keras import regularizers
import seaborn as sns
import matplotlib.pyplot as plt   
from sklearn.metrics import confusion_matrix
from keras import regularizers  
from keras.applications.inception_v3 import InceptionV3
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [74]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import re
from nltk.corpus import stopwords
# from nltk import word_tokenize
from keras.preprocessing import image
from keras.applications.vgg16 import VGG16
from keras.applications.inception_v3 import InceptionV3
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing.text import Tokenizer
import numpy as np
from keras.layers import Dense, GlobalAveragePooling2D, Embedding, LSTM, multiply
from keras.models import Model
from keras import preprocessing, Input
import os
import itertools
import numpy as np
from PIL import Image, ImageFile

In [75]:
df= pd.read_csv('D:\Internship\Mergerdata.csv')
df.head()

,Deal_Type(s),Bidder,Target,Deal_ID,Deal_Description,Year_Announced,Logan(Merger Choice),Logan(Motive Choice),MergerType,Motives,MergerType2,Motives2
0,Acquisition\nCross border\nPrivate\nTransatlantic,Abbott Laboratories,Glaxo Wellcome Inc (anesthesia business),214241,"Abbott Laboratories, the listed US based healt...",1999,Product Extension Merger,Value Creation,product-extension merger,diversification,product-extension merger,value creation
1,Acquisition\nCross border\nPublic,Abbott Laboratories,Abbott Japan Co Ltd (formerly Hokuriku Seiyaku...,84323,"Abbott Laboratories, the listed US based diagn...",2002,Market-Extension Merger,diversification,Market-Extension Merger,diversification,NaN,NaN
2,Acquisition\nCross border\nPublic\nTransatlantic,Abbott Laboratories,BASF Pharma,6576,Abbott Laboratories has agreed to acquire BASF...,2000,Horizontal Merger,Increase in financial capacity,horizontal merger,value creation,market-extension,increase financial capacity
3,Acquisition\nDomestic\nPrivate,Abbott Laboratories,BioDisplay Technologies Inc,33326,"Abbott Laboratories, the listed US based diagn...",2001,Vertical Merger,acquisition of assets,vertical merger,acquisition of assets,NaN,NaN
4,Acquisition\nCross border\nPrivate\nTransatlantic,Abbott Laboratories,Vysis Inc,10180,The US based Abbott Laboratories has agreed to...,2001,product-extension merger,diversification,product-extension merger,diversification,NaN,NaN

In [76]:
df.drop(["Deal_Type(s)","Bidder","Target","Deal_ID","MergerType","Motives","MergerType2","Motives2"], axis="columns",inplace=True)

df.rename(columns= {"Logan(Merger Choice)":"MergerType", "Logan(Motive Choice)" : "Motive"}, inplace=True)

df

,Deal_Description,Year_Announced,MergerType,Motive
0,"Abbott Laboratories, the listed US based healt...",1999,Product Extension Merger,Value Creation
1,"Abbott Laboratories, the listed US based diagn...",2002,Market-Extension Merger,diversification
2,Abbott Laboratories has agreed to acquire BASF...,2000,Horizontal Merger,Increase in financial capacity
3,"Abbott Laboratories, the listed US based diagn...",2001,Vertical Merger,acquisition of assets
4,The US based Abbott Laboratories has agreed to...,2001,product-extension merger,diversification
...,...,...,...,...
244,"Cubist Pharmaceuticals Inc, the listed US base...",2009,product-extension merger,value creation
245,"Cubist Pharmaceuticals, Inc, the listed US bas...",2007,vertical merger,Increase in financial capacity
246,"Xcyte Therapies, Inc., the listed US based bio...",2005,horizontal merger,value creation
247,"Cypress Bioscience Inc, the listed US based co...",2008,vertical merger,Increase in financial capacity
248,"CytRx Corporation, the listed (Nasdaq) US base...",2002,horizontal merger,value creation

In [77]:
df=df.drop("Year_Announced", axis= "columns")

In [78]:
stopwords = stopwords.words('english')

stopwords=set(stopwords)
stopwords.update(["abbott","company",'usd','b'])
lemmatizer = WordNetLemmatizer()

In [79]:
def datacleaning(text):
    k=''
    sent = re.sub('[^A-Za-z]',' ',text)
    sent = sent.lower()
    words = sent.split()
    words = [lemmatizer.lemmatize(word, pos='v') for word in words if word not in stopwords]
    text = ' '.join(words)
    return text

In [80]:
def convert_lower(df):
    for columns in df.columns:
        df[columns]= df[columns].apply(str.lower)
    return df

In [81]:
convert_lower(df)

,Deal_Description,MergerType,Motive
0,"abbott laboratories, the listed us based healt...",product extension merger,value creation
1,"abbott laboratories, the listed us based diagn...",market-extension merger,diversification
2,abbott laboratories has agreed to acquire basf...,horizontal merger,increase in financial capacity
3,"abbott laboratories, the listed us based diagn...",vertical merger,acquisition of assets
4,the us based abbott laboratories has agreed to...,product-extension merger,diversification
...,...,...,...
244,"cubist pharmaceuticals inc, the listed us base...",product-extension merger,value creation
245,"cubist pharmaceuticals, inc, the listed us bas...",vertical merger,increase in financial capacity
246,"xcyte therapies, inc., the listed us based bio...",horizontal merger,value creation
247,"cypress bioscience inc, the listed us based co...",vertical merger,increase in financial capacity
248,"cytrx corporation, the listed (nasdaq) us base...",horizontal merger,value creation

In [82]:
df.replace(['product-extension merger','product extension merger'], 'product', inplace=True)
df.replace( 
              ['market-extension merger','market-extension','market extension','market_extension merger'],'market',
              
             inplace=True)
df.replace(
              ['vertical merger'] , 'vertical',
              
             inplace=True)
df.replace(
              ['horizontal merger','horizontal  merger'] , 'horizontal', 
             
             inplace=True)
df.replace( 
              ['conglomerate','conglomerate merger','conglomerte'] , 'conglomerate', 
             inplace=True)

In [83]:
df

,Deal_Description,MergerType,Motive
0,"abbott laboratories, the listed us based healt...",product,value creation
1,"abbott laboratories, the listed us based diagn...",market,diversification
2,abbott laboratories has agreed to acquire basf...,horizontal,increase in financial capacity
3,"abbott laboratories, the listed us based diagn...",vertical,acquisition of assets
4,the us based abbott laboratories has agreed to...,product,diversification
...,...,...,...
244,"cubist pharmaceuticals inc, the listed us base...",product,value creation
245,"cubist pharmaceuticals, inc, the listed us bas...",vertical,increase in financial capacity
246,"xcyte therapies, inc., the listed us based bio...",horizontal,value creation
247,"cypress bioscience inc, the listed us based co...",vertical,increase in financial capacity
248,"cytrx corporation, the listed (nasdaq) us base...",horizontal,value creation

In [84]:
def encode_label(DataFrame, Label_col):
    t_y = DataFrame[Label_col].values
    print(t_y)
    Encoder = LabelEncoder()
    y = Encoder.fit_transform(t_y) 
    DataFrame[Label_col] = y

In [85]:
encode_label(df,'MergerType')

['product' 'market' 'horizontal' 'vertical' 'product' 'product' 'market'
 'market' 'vertical' 'market' 'market' 'product' 'vertical' 'market'
 'market' 'horizontal' 'vertical' 'market' 'product' 'vertical'
 'horizontal' 'vertical' 'market' 'market' 'vertical' 'market' 'vertical'
 'market' 'horizontal' 'vertical' 'product' 'vertical' 'product' 'market'
 'product' 'horizontal' 'market' 'product' 'horizontal' 'market'
 'horizontal' 'market' 'horizontal' 'market' 'vertical' 'vertical'
 'market' 'market' 'market' 'product' 'vertical' 'product' 'market'
 'vertical' 'market' 'horizontal' 'market' 'horizontal' 'vertical'
 'market' 'product' 'market' 'product' 'product' 'conglomerate' 'vertical'
 'product' 'product' 'horizontal' 'market' 'market' 'conglomerate'
 'horizontal' 'vertical' 'market' 'product' 'product' 'product' 'vertical'
 'market' 'vertical' 'vertical' 'product' 'horizontal' 'vertical' 'market'
 'vertical' 'horizontal' 'horizontal' 'conglomerate' 'product' 'market'
 'market' 'product' 'product' 'vertical' 'product' 'market' 'product'
 'vertical' 'product' 'market' 'market' 'product' 'conglomerate' 'market'
 'market' 'product' 'product' 'horizontal' 'market' 'product' 'market'
 'product' 'product' 'vertical' 'product' 'market' 'market' 'market'
 'horizontal' 'market' 'product' 'product' 'product' 'product' 'vertical'
 'market' 'market' 'horizontal' 'market' 'vertical' 'product' 'product'
 'market' 'market' 'product' 'market' 'vertical' 'product' 'product'
 'horizontal' 'market' 'market' 'product' 'vertical' 'market' 'market'
 'horizontal' 'vertical' 'horizontal' 'market' 'product' 'horizontal'
 'horizontal' 'product' 'horizontal' 'product' 'product' 'product'
 'market' 'product' 'market' 'product' 'product' 'horizontal' 'product'
 'product' 'market' 'conglomerate' 'market' 'market' 'horizontal'
 'vertical' 'market' 'vertical' 'vertical' 'horizontal' 'product'
 'product' 'product' 'horizontal' 'product' 'product' 'product'
 'horizontal' 'horizontal' 'market' 'market' 'market' 'vertical' 'product'
 'vertical' 'product' 'horizontal' 'product' 'market' 'product' 'market'
 'product' 'product' 'product' 'product' 'vertical' 'horizontal'
 'horizontal' 'horizontal' 'product' 'horizontal' 'horizontal'
 'horizontal' 'product' 'market' 'product' 'product' 'product'
 'horizontal' 'market' 'horizontal' 'market' 'product' 'product'
 'horizontal' 'vertical' 'horizontal' 'product' 'market' 'vertical'
 'product' 'product' 'market' 'vertical' 'product' 'product' 'vertical'
 'product' 'horizontal' 'horizontal' 'vertical' 'product' 'horizontal'
 'market' 'horizontal' 'product' 'product' 'vertical' 'horizontal'
 'vertical' 'horizontal']

In [86]:
df

,Deal_Description,MergerType,Motive
0,"abbott laboratories, the listed us based healt...",3,value creation
1,"abbott laboratories, the listed us based diagn...",2,diversification
2,abbott laboratories has agreed to acquire basf...,1,increase in financial capacity
3,"abbott laboratories, the listed us based diagn...",4,acquisition of assets
4,the us based abbott laboratories has agreed to...,3,diversification
...,...,...,...
244,"cubist pharmaceuticals inc, the listed us base...",3,value creation
245,"cubist pharmaceuticals, inc, the listed us bas...",4,increase in financial capacity
246,"xcyte therapies, inc., the listed us based bio...",1,value creation
247,"cypress bioscience inc, the listed us based co...",4,increase in financial capacity
248,"cytrx corporation, the listed (nasdaq) us base...",1,value creation

In [91]:
df["Deal_Description"]=df["Deal_Description"].apply(datacleaning)

In [92]:
df

,Deal_Description,MergerType,Motive
0,laboratories list us base health care discover...,3,value creation
1,laboratories list us base diagnostics producer...,2,diversification
2,laboratories agree acquire basf pharma bn basf...,1,increase in financial capacity
3,laboratories list us base diagnostics producer...,4,acquisition of assets
4,us base laboratories agree acquire stake vysis...,3,diversification
...,...,...,...
244,cubist pharmaceuticals inc list us base biopha...,3,value creation
245,cubist pharmaceuticals inc list us base biopha...,4,increase in financial capacity
246,xcyte therapies inc list us base biotechnology...,1,value creation
247,cypress bioscience inc list us base engage dev...,4,increase in financial capacity
248,cytrx corporation list nasdaq us base biopharm...,1,value creation

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df["Deal_Description"], df["MergerType"], test_size = 0.20, random_state = 32, stratify =df["MergerType"])

76     boston apply biosystems list us base develop m...
126    scandipharm inc receive tender offer axcan pha...
111    sanofi aventis sa list france base pharmaceuti...
9      laboratories via subsidiary capital india ltd ...
25     inverness medical innovations inc us list manu...
                             ...
50     amerisourcebergen corporation list us base pha...
23     albany molecular research inc amri list us bas...
5      btender offer kos pharmaceuticals inc florida ...
117    tender offer genzyme corp genz massachusetts c...
222    agt biosciences ltd list australian biotechnol...
Name: Deal_Description, Length: 199, dtype: object

In [95]:
GLOVE_DIR = "D:\Internship\\glove.6B"
EMBEDDING_DIM = 50
#doubt on embedding_dim

In [96]:
def read_data(file_name):
  #Opening file
    with open(file_name,'r', encoding="utf8") as f:
      #Creating empty set and dictonary for vocab and word respectively
        word_vocab = set() 
        word2vector = {}
        #Iterating over each line of file
        for line in f:
            #Spliting lines
            line_ = line.strip() 
            #Splitting words
            words_Vec = line_.split()            
            word_vocab.add(words_Vec[0])
            word2vector[words_Vec[0]] = np.array(words_Vec[1:],dtype=float)
    print("Total Words in DataSet:",len(word_vocab))
    return word_vocab,word2vector

In [97]:
vocab, w2v = read_data(os.path.join(GLOVE_DIR, "glove.6B.50d.txt"))

Total Words in DataSet: 400000

In [102]:
# Vectorising text
# process the whole observation into single list
X_train_list=list(X_train)
X_test_list = list(X_test)

In [103]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train_list)
word_index = tokenizer.word_index
num_tokens = len(word_index) +1

In [104]:
X_train_sequences = tokenizer.texts_to_sequences(X_train_list)
X_test_sequences  = tokenizer.texts_to_sequences(X_test_list)

In [110]:
maxlen = 100

X_train = pad_sequences(X_train_sequences, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test_sequences, padding='post', maxlen=maxlen)
print(X_train[0, :])

[ 466  243  287   10    3    1   60   24  983    1  554    7  516   57
 1898  984    8    3    1  188 1168  984    1  554 1168  434  609    1
 1899 1900 1169  609    1  435    6  466  984   87 1169   86    7 1901
  259  107  189  157   43  985  466  984  158  329 1170 1169 1171  120
  986  288 1168  610   42  330    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]

In [111]:
#Creating embeddding weight matrix
embedding_matrix = np.zeros((num_tokens, EMBEDDING_DIM))

for word, i in word_index.items():
    embedding_vector = w2v.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [112]:
embedding_layer = tf.keras.layers.Embedding(num_tokens,
                                          EMBEDDING_DIM,
                                          weights=[embedding_matrix],
                                          input_length=maxlen,
                                          trainable=False)

In [113]:
from tensorflow.keras.layers import Conv1D, Bidirectional, LSTM, Dense, Input, Dropout
from tensorflow.keras.layers import SpatialDropout1D
from tensorflow.keras.callbacks import ModelCheckpoint

In [133]:
sequence_input = Input(shape=(maxlen, ), dtype='int32')
embedding_sequences = embedding_layer(sequence_input)
x = SpatialDropout1D(0.2)(embedding_sequences)
x = Conv1D(64, 5, activation='relu')(x)
x = Bidirectional(LSTM(64, dropout=0.2, recurrent_dropout=0.2))(x)
x = Dense(512, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(512, activation='relu')(x)
outputs = Dense(1, activation='softmax')(x)
model = tf.keras.Model(sequence_input, outputs)

In [134]:
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.01), loss='binary_crossentropy',
              metrics=['accuracy'])

In [135]:
model_fit = model.fit(X_train, y_train, batch_size=10, epochs=10,
                    validation_data=(X_test, y_test))

Epoch 1/10
20/20 [==============================] - 7s 81ms/step - loss: -21222.2188 - accuracy: 0.1910 - val_loss: -98422.9062 - val_accuracy: 0.1800
Epoch 2/10
20/20 [==============================] - 1s 56ms/step - loss: -458030.6875 - accuracy: 0.1910 - val_loss: -1213654.5000 - val_accuracy: 0.1800
Epoch 3/10
20/20 [==============================] - 1s 57ms/step - loss: -2896539.7500 - accuracy: 0.1910 - val_loss: -5756583.5000 - val_accuracy: 0.1800
Epoch 4/10
20/20 [==============================] - 1s 60ms/step - loss: -10241065.0000 - accuracy: 0.1910 - val_loss: -17592528.0000 - val_accuracy: 0.1800
Epoch 5/10
20/20 [==============================] - 1s 58ms/step - loss: -27559448.0000 - accuracy: 0.1910 - val_loss: -41438020.0000 - val_accuracy: 0.1800
Epoch 6/10
20/20 [==============================] - 1s 59ms/step - loss: -58275608.0000 - accuracy: 0.1910 - val_loss: -83343976.0000 - val_accuracy: 0.1800
Epoch 7/10
20/20 [==============================] - 1s 58ms/step - loss: -107374992.0000 - accuracy: 0.1910 - val_loss: -145882848.0000 - val_accuracy: 0.1800
Epoch 8/10
20/20 [==============================] - 1s 59ms/step - loss: -182124240.0000 - accuracy: 0.1910 - val_loss: -237529824.0000 - val_accuracy: 0.1800
Epoch 9/10
20/20 [==============================] - 2s 97ms/step - loss: -283294272.0000 - accuracy: 0.1910 - val_loss: -362612992.0000 - val_accuracy: 0.1800
Epoch 10/10
20/20 [==============================] - 2s 113ms/step - loss: -420100000.0000 - accuracy: 0.1910 - val_loss: -526382624.0000 - val_accuracy: 0.1800